# Generated by Django 4.2.5 on 2023-09-29 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('size', models.IntegerField()),
                ('video_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='media/')),
                ('extension', models.CharField(max_length=5)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
