# Generated by Django 4.2.5 on 2023-09-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrome_ext_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AlterField(
            model_name='video',
            name='extension',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
