# Generated by Django 4.2.5 on 2023-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrome_ext_app', '0002_remove_video_url_remove_video_video_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=270, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video File')),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
